MINER: Trex
TrexAPI: http://127.0.0.1:4067
TrexAPIPASS: YourWebGuiPassword
SUDO_PASS: "0"
MQTT:
  TOPIC: miner2mqtt/rig0
  HOST: 192.168.0.120
  USERNAME: mqttusername
  PASS: mqttpass
INTERVAL: 300
INCLUDE:
- active_pool
- gpus
- sys_params
EXCLUDE: {}
